[2023-09-21T09:47:23.966+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.dbt_run_tests manual__2023-09-21T09:45:11.206051+00:00 [queued]>
[2023-09-21T09:47:23.981+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.dbt_run_tests manual__2023-09-21T09:45:11.206051+00:00 [queued]>
[2023-09-21T09:47:23.981+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T09:47:24.012+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run_tests> on 2023-09-21 09:45:11.206051+00:00
[2023-09-21T09:47:24.019+0000] {standard_task_runner.py:57} INFO - Started process 288 to run task
[2023-09-21T09:47:24.024+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'dbt_run_tests', 'manual__2023-09-21T09:45:11.206051+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp89dg8vof']
[2023-09-21T09:47:24.027+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask dbt_run_tests
[2023-09-21T09:47:24.095+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.dbt_run_tests manual__2023-09-21T09:45:11.206051+00:00 [running]> on host 2cbbdff68ad8
[2023-09-21T09:47:24.240+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='dbt_run_tests' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T09:45:11.206051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T09:45:11.206051+00:00'
[2023-09-21T09:47:24.242+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-21T09:47:24.243+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt test --profiles-dir /.dbt --project-dir /dbt_project']
[2023-09-21T09:47:24.259+0000] {subprocess.py:86} INFO - Output:
[2023-09-21T09:47:29.297+0000] {subprocess.py:93} INFO - [0m09:47:29  Running with dbt=1.5.3
[2023-09-21T09:47:29.520+0000] {subprocess.py:93} INFO - [0m09:47:29  Registered adapter: postgres=1.5.3
[2023-09-21T09:47:29.789+0000] {subprocess.py:93} INFO - [0m09:47:29  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-09-21T09:47:29.789+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-09-21T09:47:29.789+0000] {subprocess.py:93} INFO - - models.dbt_supermarket_data_engineering.example
[2023-09-21T09:47:29.831+0000] {subprocess.py:93} INFO - [0m09:47:29  Found 5 models, 0 tests, 1 snapshot, 0 analyses, 718 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics, 0 groups
[2023-09-21T09:47:29.835+0000] {subprocess.py:93} INFO - [0m09:47:29
[2023-09-21T09:47:29.837+0000] {subprocess.py:93} INFO - [0m09:47:29  Nothing to do. Try checking your model configs and model specification args
[2023-09-21T09:47:32.365+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-21T09:47:32.405+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=dbt_run_tests, execution_date=20230921T094511, start_date=20230921T094723, end_date=20230921T094732
[2023-09-21T09:47:32.455+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-21T09:47:32.489+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
