[2023-09-21T09:42:09.475+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.dbt_run_tests manual__2023-09-21T09:40:20.985880+00:00 [queued]>
[2023-09-21T09:42:09.491+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.dbt_run_tests manual__2023-09-21T09:40:20.985880+00:00 [queued]>
[2023-09-21T09:42:09.491+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T09:42:09.518+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run_tests> on 2023-09-21 09:40:20.985880+00:00
[2023-09-21T09:42:09.525+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2023-09-21T09:42:09.531+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'dbt_run_tests', 'manual__2023-09-21T09:40:20.985880+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp3cm1rt0b']
[2023-09-21T09:42:09.537+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask dbt_run_tests
[2023-09-21T09:42:09.623+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.dbt_run_tests manual__2023-09-21T09:40:20.985880+00:00 [running]> on host 2cbbdff68ad8
[2023-09-21T09:42:09.816+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='dbt_run_tests' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T09:40:20.985880+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T09:40:20.985880+00:00'
[2023-09-21T09:42:09.820+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-21T09:42:09.820+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt test --profiles-dir /.dbt --project-dir /dbt_project']
[2023-09-21T09:42:09.848+0000] {subprocess.py:86} INFO - Output:
[2023-09-21T09:42:14.401+0000] {subprocess.py:93} INFO - [0m09:42:14  Running with dbt=1.5.3
[2023-09-21T09:42:14.662+0000] {subprocess.py:93} INFO - [0m09:42:14  Registered adapter: postgres=1.5.3
[2023-09-21T09:42:14.967+0000] {subprocess.py:93} INFO - [0m09:42:14  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-09-21T09:42:14.967+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-09-21T09:42:14.967+0000] {subprocess.py:93} INFO - - models.dbt_supermarket_data_engineering.example
[2023-09-21T09:42:15.020+0000] {subprocess.py:93} INFO - [0m09:42:15  Found 5 models, 0 tests, 1 snapshot, 0 analyses, 718 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics, 0 groups
[2023-09-21T09:42:15.023+0000] {subprocess.py:93} INFO - [0m09:42:15
[2023-09-21T09:42:15.025+0000] {subprocess.py:93} INFO - [0m09:42:15  Nothing to do. Try checking your model configs and model specification args
[2023-09-21T09:42:16.783+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-21T09:42:16.831+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=dbt_run_tests, execution_date=20230921T094020, start_date=20230921T094209, end_date=20230921T094216
[2023-09-21T09:42:16.907+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-21T09:42:16.944+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
