[2023-09-20T11:37:17.937+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.run_dbt manual__2023-09-20T11:36:55.975595+00:00 [queued]>
[2023-09-20T11:37:17.952+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.run_dbt manual__2023-09-20T11:36:55.975595+00:00 [queued]>
[2023-09-20T11:37:17.952+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T11:37:18.154+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_dbt> on 2023-09-20 11:36:55.975595+00:00
[2023-09-20T11:37:18.160+0000] {standard_task_runner.py:57} INFO - Started process 149 to run task
[2023-09-20T11:37:18.164+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'run_dbt', 'manual__2023-09-20T11:36:55.975595+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpt3x4gpv5']
[2023-09-20T11:37:18.170+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask run_dbt
[2023-09-20T11:37:18.248+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.run_dbt manual__2023-09-20T11:36:55.975595+00:00 [running]> on host 1240b9faba90
[2023-09-20T11:37:18.379+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T11:36:55.975595+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T11:36:55.975595+00:00'
[2023-09-20T11:37:18.383+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-20T11:37:18.384+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo dbt run --profiles-dir /.dbt --project-dir /opt/***/dbt_project']
[2023-09-20T11:37:18.397+0000] {subprocess.py:86} INFO - Output:
[2023-09-20T11:37:18.585+0000] {subprocess.py:93} INFO - 
[2023-09-20T11:37:18.585+0000] {subprocess.py:93} INFO - We trust you have received the usual lecture from the local System
[2023-09-20T11:37:18.586+0000] {subprocess.py:93} INFO - Administrator. It usually boils down to these three things:
[2023-09-20T11:37:18.586+0000] {subprocess.py:93} INFO - 
[2023-09-20T11:37:18.586+0000] {subprocess.py:93} INFO -     #1) Respect the privacy of others.
[2023-09-20T11:37:18.587+0000] {subprocess.py:93} INFO -     #2) Think before you type.
[2023-09-20T11:37:18.587+0000] {subprocess.py:93} INFO -     #3) With great power comes great responsibility.
[2023-09-20T11:37:18.587+0000] {subprocess.py:93} INFO - 
[2023-09-20T11:37:18.594+0000] {subprocess.py:93} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2023-09-20T11:37:18.595+0000] {subprocess.py:93} INFO - sudo: a password is required
[2023-09-20T11:37:18.595+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-20T11:37:18.610+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-20T11:37:18.616+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=main_dag, task_id=run_dbt, execution_date=20230920T113655, start_date=20230920T113717, end_date=20230920T113718
[2023-09-20T11:37:18.686+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 149)
[2023-09-20T11:37:18.696+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T11:37:18.737+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
